"use client"
import Link from "next/link";
import { usePathname } from "next/navigation";
import './styles.css'
import { useState } from "react";
// export const metadata = {
//     title: 'Next.js',
//     description: 'Generated by Next.js',
//   }

  const links=[
    {
        name:"SignUp",
        route:"signup"
    },
    {
        name:"SignIn",
        route:"signin"
    },
    {
        name:"Forgot-Password",
        route:"forgot-password"
    },
  ]
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    const pathname=usePathname();
    const [name, setName] = useState<string>("")

    return (
    
            <div>
              <div>
                <input type="text" value={name} onChange={e=>setName(e.target.value)} name="" id="" />
              </div>
                
            {
                links.map((elm,ind)=>{
                    const isActive:boolean=pathname.startsWith(elm.route)
                   return <Link href={`/${elm.route}`} key={ind} className={isActive?"font-red-600":"font-blue-500"}>{elm.name}</Link>; 
                })
            }

          {children}
            </div>
       
    )
  }
  